### ISSUE TITLE
undefined method 'cache' for Rails::Module when using Sinatra

### ISSUE THREAD

**Issue by bogdanRada** [sinisterchipmunk/gravatar#19]
This is the erorr i get when i try to do this using Sinatra framework
```ruby
 Gravatar.new(current_user.email).image_url(:ssl => true)
```

 NoMethodError - undefined method `cache' for Rails:Module:
gems/gravatar-ultimate-2.0.0/lib/gravatar/cache.rb:101:in `default_cache_instance'
gems/gravatar-ultimate-2.0.0/lib/gravatar/cache.rb:109:in `cache'
gems/gravatar-ultimate-2.0.0/lib/gravatar.rb:44:in `initialize'

Can this be fixed? or is there any work-around? Please help.

**Comment by bogdanRada** [comment]
this was happening with activesupport 4.2.2 and i was able to fix it by adding to Gemfile, the gem 'railties' and i had to require before this gem

```ruby
require 'rails/all'
```
and that seems to do the trick.  I can close this issue
